//
// CharacterList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CharacterList: Codable {

    /** The number of total available characters in this list. Will always be greater than or equal to the \&quot;returned\&quot; value. */
    public var available: Int?
    /** The number of characters returned in this collection (up to 20). */
    public var returned: Int?
    /** The path to the full list of characters in this collection. */
    public var collectionURI: String?
    /** The list of returned characters in this collection. */
    public var items: [CharacterSummary]?

    public init(available: Int? = nil, returned: Int? = nil, collectionURI: String? = nil, items: [CharacterSummary]? = nil) {
        self.available = available
        self.returned = returned
        self.collectionURI = collectionURI
        self.items = items
    }


}
