//
// ComicDate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ComicDate: Codable {

    /** A description of the date (e.g. onsale date, FOC date). */
    public var type: String?
    /** The date. */
    public var date: Date?

    public init(type: String? = nil, date: Date? = nil) {
        self.type = type
        self.date = date
    }


}
