//
// ComicSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ComicSummary: Codable {

    /** The path to the individual comic resource. */
    public var resourceURI: String?
    /** The canonical name of the comic. */
    public var name: String?

    public init(resourceURI: String? = nil, name: String? = nil) {
        self.resourceURI = resourceURI
        self.name = name
    }


}
