//
// Creator.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Creator: Codable {

    /** The unique ID of the creator resource. */
    public var _id: Int?
    /** The first name of the creator. */
    public var firstName: String?
    /** The middle name of the creator. */
    public var middleName: String?
    /** The last name of the creator. */
    public var lastName: String?
    /** The suffix or honorific for the creator. */
    public var suffix: String?
    /** The full name of the creator (a space-separated concatenation of the above four fields). */
    public var fullName: String?
    /** The date the resource was most recently modified. */
    public var modified: Date?
    /** The canonical URL identifier for this resource. */
    public var resourceURI: String?
    /** A set of public web site URLs for the resource. */
    public var urls: [Url]?
    public var thumbnail: Image?
    public var series: SeriesList?
    public var stories: StoryList?
    public var comics: ComicList?
    public var events: EventList?

    public init(_id: Int? = nil, firstName: String? = nil, middleName: String? = nil, lastName: String? = nil, suffix: String? = nil, fullName: String? = nil, modified: Date? = nil, resourceURI: String? = nil, urls: [Url]? = nil, thumbnail: Image? = nil, series: SeriesList? = nil, stories: StoryList? = nil, comics: ComicList? = nil, events: EventList? = nil) {
        self._id = _id
        self.firstName = firstName
        self.middleName = middleName
        self.lastName = lastName
        self.suffix = suffix
        self.fullName = fullName
        self.modified = modified
        self.resourceURI = resourceURI
        self.urls = urls
        self.thumbnail = thumbnail
        self.series = series
        self.stories = stories
        self.comics = comics
        self.events = events
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case firstName
        case middleName
        case lastName
        case suffix
        case fullName
        case modified
        case resourceURI
        case urls
        case thumbnail
        case series
        case stories
        case comics
        case events
    }

}
