//
// Event.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Event: Codable {

    /** The unique ID of the event resource. */
    public var _id: Int?
    /** The title of the event. */
    public var title: String?
    /** A description of the event. */
    public var _description: String?
    /** The canonical URL identifier for this resource. */
    public var resourceURI: String?
    /** A set of public web site URLs for the event. */
    public var urls: [Url]?
    /** The date the resource was most recently modified. */
    public var modified: Date?
    /** The date of publication of the first issue in this event. */
    public var start: Date?
    /** The date of publication of the last issue in this event. */
    public var end: Date?
    public var thumbnail: Image?
    public var comics: ComicList?
    public var stories: StoryList?
    public var series: SeriesList?
    public var characters: CharacterList?
    public var creators: CreatorList?
    public var next: EventSummary?
    public var previous: EventSummary?

    public init(_id: Int? = nil, title: String? = nil, _description: String? = nil, resourceURI: String? = nil, urls: [Url]? = nil, modified: Date? = nil, start: Date? = nil, end: Date? = nil, thumbnail: Image? = nil, comics: ComicList? = nil, stories: StoryList? = nil, series: SeriesList? = nil, characters: CharacterList? = nil, creators: CreatorList? = nil, next: EventSummary? = nil, previous: EventSummary? = nil) {
        self._id = _id
        self.title = title
        self._description = _description
        self.resourceURI = resourceURI
        self.urls = urls
        self.modified = modified
        self.start = start
        self.end = end
        self.thumbnail = thumbnail
        self.comics = comics
        self.stories = stories
        self.series = series
        self.characters = characters
        self.creators = creators
        self.next = next
        self.previous = previous
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case _description = "description"
        case resourceURI
        case urls
        case modified
        case start
        case end
        case thumbnail
        case comics
        case stories
        case series
        case characters
        case creators
        case next
        case previous
    }

}
