//
// EventSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EventSummary: Codable {

    /** The path to the individual event resource. */
    public var resourceURI: String?
    /** The name of the event. */
    public var name: String?

    public init(resourceURI: String? = nil, name: String? = nil) {
        self.resourceURI = resourceURI
        self.name = name
    }


}
