//
// Image.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Image: Codable {

    /** The directory path of to the image. */
    public var path: String?
    /** The file extension for the image. */
    public var _extension: String?

    public init(path: String? = nil, _extension: String? = nil) {
        self.path = path
        self._extension = _extension
    }

    public enum CodingKeys: String, CodingKey { 
        case path
        case _extension = "extension"
    }

}
