//
// SeriesSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SeriesSummary: Codable {

    /** The path to the individual series resource. */
    public var resourceURI: String?
    /** The canonical name of the series. */
    public var name: String?

    public init(resourceURI: String? = nil, name: String? = nil) {
        self.resourceURI = resourceURI
        self.name = name
    }


}
