//
// Series.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Series: Codable {

    /** The unique ID of the series resource. */
    public var _id: Int?
    /** The canonical title of the series. */
    public var title: String?
    /** A description of the series. */
    public var _description: String?
    /** The canonical URL identifier for this resource. */
    public var resourceURI: String?
    /** A set of public web site URLs for the resource. */
    public var urls: [Url]?
    /** The first year of publication for the series. */
    public var startYear: Int?
    /** The last year of publication for the series (conventionally, 2099 for ongoing series) . */
    public var endYear: Int?
    /** The age-appropriateness rating for the series. */
    public var rating: String?
    /** The date the resource was most recently modified. */
    public var modified: Date?
    public var thumbnail: Image?
    public var comics: ComicList?
    public var stories: StoryList?
    public var events: EventList?
    public var characters: CharacterList?
    public var creators: CreatorList?
    public var next: SeriesSummary?
    public var previous: SeriesSummary?

    public init(_id: Int? = nil, title: String? = nil, _description: String? = nil, resourceURI: String? = nil, urls: [Url]? = nil, startYear: Int? = nil, endYear: Int? = nil, rating: String? = nil, modified: Date? = nil, thumbnail: Image? = nil, comics: ComicList? = nil, stories: StoryList? = nil, events: EventList? = nil, characters: CharacterList? = nil, creators: CreatorList? = nil, next: SeriesSummary? = nil, previous: SeriesSummary? = nil) {
        self._id = _id
        self.title = title
        self._description = _description
        self.resourceURI = resourceURI
        self.urls = urls
        self.startYear = startYear
        self.endYear = endYear
        self.rating = rating
        self.modified = modified
        self.thumbnail = thumbnail
        self.comics = comics
        self.stories = stories
        self.events = events
        self.characters = characters
        self.creators = creators
        self.next = next
        self.previous = previous
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case _description = "description"
        case resourceURI
        case urls
        case startYear
        case endYear
        case rating
        case modified
        case thumbnail
        case comics
        case stories
        case events
        case characters
        case creators
        case next
        case previous
    }

}
