//
// SeriesList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SeriesList: Codable {

    /** The number of total available series in this list. Will always be greater than or equal to the \&quot;returned\&quot; value. */
    public var available: Int?
    /** The number of series returned in this collection (up to 20). */
    public var returned: Int?
    /** The path to the full list of series in this collection. */
    public var collectionURI: String?
    /** The list of returned series in this collection. */
    public var items: [SeriesSummary]?

    public init(available: Int? = nil, returned: Int? = nil, collectionURI: String? = nil, items: [SeriesSummary]? = nil) {
        self.available = available
        self.returned = returned
        self.collectionURI = collectionURI
        self.items = items
    }


}
