//
// StorySummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StorySummary: Codable {

    /** The path to the individual story resource. */
    public var resourceURI: String?
    /** The canonical name of the story. */
    public var name: String?
    /** The type of the story (interior or cover). */
    public var type: String?

    public init(resourceURI: String? = nil, name: String? = nil, type: String? = nil) {
        self.resourceURI = resourceURI
        self.name = name
        self.type = type
    }


}
