//
// Story.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Story: Codable {

    /** The unique ID of the story resource. */
    public var _id: Int?
    /** The story title. */
    public var title: String?
    /** A short description of the story. */
    public var _description: String?
    /** The canonical URL identifier for this resource.  */
    public var resourceURI: String?
    /** The story type e.g. interior story, cover, text story. */
    public var type: String?
    /** The date the resource was most recently modified. */
    public var modified: Date?
    public var thumbnail: Image?
    public var comics: ComicList?
    public var series: SeriesList?
    public var events: EventList?
    public var characters: CharacterList?
    public var creators: CreatorList?
    public var originalissue: ComicSummary?

    public init(_id: Int? = nil, title: String? = nil, _description: String? = nil, resourceURI: String? = nil, type: String? = nil, modified: Date? = nil, thumbnail: Image? = nil, comics: ComicList? = nil, series: SeriesList? = nil, events: EventList? = nil, characters: CharacterList? = nil, creators: CreatorList? = nil, originalissue: ComicSummary? = nil) {
        self._id = _id
        self.title = title
        self._description = _description
        self.resourceURI = resourceURI
        self.type = type
        self.modified = modified
        self.thumbnail = thumbnail
        self.comics = comics
        self.series = series
        self.events = events
        self.characters = characters
        self.creators = creators
        self.originalissue = originalissue
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case _description = "description"
        case resourceURI
        case type
        case modified
        case thumbnail
        case comics
        case series
        case events
        case characters
        case creators
        case originalissue
    }

}
