//
// TextObject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TextObject: Codable {

    /** The canonical type of the text object (e.g. solicit text, preview text, etc.). */
    public var type: String?
    /** The IETF language tag denoting the language the text object is written in. */
    public var language: String?
    /** The text. */
    public var text: String?

    public init(type: String? = nil, language: String? = nil, text: String? = nil) {
        self.type = type
        self.language = language
        self.text = text
    }


}
